export enum actionsTypes {
    FETCH_QUIZES_START = "FETCH_QUIZES_START",
    FETCH_QUIZES_SUCCESS = "FETCH_QUIZES_SUCCESS",
    FETCH_QUIZES_ERROR = "FETCH_QUIZES_ERROR",
    FETCH_QUIZ_START = "FETCH_QUIZ_START",
    FETCH_QUIZ_SUCCESS = "FETCH_QUIZ_SUCCESS",
    FETCH_QUIZ_ERROR = "FETCH_QUIZ_ERROR",
    RETRY_QUIZ="RETRY_QUIZ",
    ANSWER_SUCCESS="ANSWER_SUCCESS",
    ANSWER_ERROR="ANSWER_ERROR",
    QUIZ_FINISH="QUIZ_FINISH",
    GO_NEXT_QUESTION="GO_NEXT_QUESTION",
    CREATE_QUIZ_QUESTION="CREATE_QUIZ_QUESTION",
    CLEAR_QUIZ_CREATE="CLEAR_QUIZ_CREATE",
    AUTH_SUCCESS="AUTH_SUCCESS",
    AUTH_LOGOUT="AUTH_LOGOUT"
}